alias t="Thunar ."
alias e="vim ."
alias f="open"
alias v="vim"
alias switchtty="systemctl stop graphical.target; systemctl start multi-user.target"
alias switchgraphic="systemctl stop multi-user.target; systemctl start graphical.target"
