set background=dark
set ignorecase
set smartcase
syntax on 
colorscheme gruvbox
set relativenumber 
set nu rnu
filetype plugin indent on
let g:netrw_bufsettings = 'noma nomod nu rnu nowrap ro nobl'
" Custom mappings
" ----------------
" Explorer
nnoremap <silent> ,<space> :Explore<CR>
nnoremap <silent> ,v :Lex<CR>
" Launch terminal (letter b > bash)
nnoremap <silent> ,b :terminal<CR>
" Open new tab
nnoremap <silent> ,t :tabnew<CR>
" ----------------
set clipboard=unnamedplus
set encoding=utf-8
hi clear SpellBad
hi SpellBad cterm=underline
" Set style for gVim
hi SpellBad gui=undercurl
